import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, Typography } from '@mui/material'
import Navbar from '@/components/Navbar/Navbar'

import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/pagination";



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const data = require("../../data/db.json")


  const boards = data.boards[0].columns
  // const board = data.boards



  console.log(data.boards[0].columns);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >


      </main>
    </>
  )
}
